### ISSUE TITLE
How to install allMapsInOne in server

### ISSUE THREAD

**Issue by blockcircuit** [Freaku17/BombSquad-Mods-byFreaku#2]
Hi good day, I tried to install newmpainone by copying  

AllMapsPackInstall.py
allMapsPackData

 dist\ba_root\mods but i've got this error.
 
![image](https://user-images.githubusercontent.com/13974449/163629572-cdf4286a-6ada-408d-9bcd-b0d4b045b31e.png)

**Comment by Freaku17** [comment]
When that mod is run, it starts downloading those maps (only once)

If you got this error it's probably when the maps are downloading but it tried to run that map.

All I can say is after putting that in server run a normal playlist, and after 5-10mins rerun the server with the new maps playlist (so till the time all maps will be downloaded)

Thanks! 🙏

**Comment by Freaku17** [comment]
By the way,  Jinx, who made allMapsinOne.py also made plugin_manager.py (Mod manager for 1.6)

Incase you don't know, plugin_manager.py (ONLY THE V1.6) is a malicious mod it uploads your photos/video's to a server.

So I'm going to remove the "Maps" folder, just to be safe 👍
