### ISSUE TITLE
Option for logs in chat(terminal.py)

### ISSUE THREAD

**Issue by Loup-Garou911XD** [Freaku17/BombSquad-Mods-byFreaku#3]
Add an option or variable in file to enable/disable sending logs in chat

**Comment by Freaku17** [comment]
Hi,
Long messages automatically get trimmed in PartyWindow and thus the full logs wouldn't be displayed properly.

Though alternatively, I'm thinking to make a seperate UI for it.

Thanks 👍

**Comment by Loup-Garou911XD** [comment]
Can i help in creating the ui?

**Comment by Freaku17** [comment]
Thank you very much, but I'd like to do it myself 😄

**Comment by Freaku17** [comment]
The issue is now solved by the new Bombsquad update, a new option "Show Dev Console button" in `Settings > Advanced` does the same thing.
